import {EditorView} from 'https://jspm.dev/@codemirror/view';
//import {Extension} from 'https://jspm.dev/@codemirror/state';
import {HighlightStyle,syntaxHighlighting} from 'https://jspm.dev/@codemirror/language';
import {tags as t} from 'https://jspm.dev/@lezer/highlight';

export const darculaTheme=EditorView.theme({
  '&':{color:'#a9b7c6',backgroundColor:'#2b2b2b'},
  '.cm-content':{caretColor:'#bbbbbb'},
  '.cm-content,.cm-dropCursor':{borderLeftColor:'#bbbbbb'},
  '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection':{backgroundColor:'#214283'},
  '.cm-panels':{backgroundColor:'#313335',color:'#a4a3a3'},
  '.cm-panels.cm-panels-top':{borderBottom:'2px solid black'},
  '.cm-panels.cm-panels-bottom':{borderTop:'2px solid black'},
  '.cm-searchMatch':{backgroundColor:'#155221',outline:'1px solid #00530d'},
  '.cm-searchMatch.cm-searchMatch-selected':{backgroundColor:'#214283',outline:'1px solid #bbbbbb'},
  '.cm-activeLine':{backgroundColor:'#323232'},
  '.cm-selectionMatch':{backgroundColor:'#214283'},
  '&.cm-focused .cm-matchingBracket, &.cm-focused .cm-nonmatchingBracket':{backgroundColor:'#803b514d',outline:'1px solid #80ffef28'},
  '.cm-gutters':{backgroundColor:'#313335',color:'#606366',border:'#4d4d4d'},
  '.cm-activeLineGutter':{backgroundColor:'#323232'},
  '.cm-foldPlaceholder':{backgroundColor:'#3a3a3a',border:'none',color:'#8c8c8c'},
  '.cm-tooltip':{border:'#4d4d4d',backgroundColor:'#313335'},
  '.cm-tooltip .cm-tooltip-arrow:before':{borderTopColor:'transparent',borderBottomColor:'transparent'},
  '.cm-tooltip .cm-tooltip-arrow:after':{borderTopColor:'#313335',borderBottomColor:'#313335'},
  '.cm-tooltip-autocomplete':{'& > ul > li[aria-selected]':{backgroundColor:'#46484A',color:'#a9b7c6'}}
},{dark:true});

export const darculaHighlightStyle = HighlightStyle.define([
  {tag:t.comment,color:'#808080'},
  {tag:t.blockComment,color:'#808080'},
  {tag:t.docComment,color:'#629755'},
  {tag:t.name,color:'#a9b7c6'},
  {tag:t.variableName,color:'#a9b7c6'},
  {tag:t.typeName,color:'#a9b7c6'},
  {tag:t.tagName,color:'#e8bf6a'},
  // {tag:t.propertyName,color:'#a9b7c6'},
  {tag:t.propertyName,color:'#9876aa'},
  {tag:t.attributeName,color:'#bababa'},
  {tag:t.className,color:'#a9b7c6'},
  {tag:t.labelName,color:'#a9b7c6'},
  {tag:t.namespace,color:'#a9b7c6'},
  {tag:t.macroName,color:'#bbb529'},
  {tag:t.literal,color:'#6a8759'},
  {tag:t.string,color:'#6a8759'},
  {tag:t.docString,color:'#629755'},
  {tag:t.character,color:'#6d9cbe'},
  {tag:t.attributeValue,color:'#a5c261'},
  {tag:t.number,color:'#6897bb'},
  {tag:t.integer,color:'#6897bb'},
  {tag:t.float,color:'#6897bb'},
  {tag:t.bool,color:'#cc7832'},
  {tag:t.regexp,color:'#6a8759',fontStyle:'italic'},
  {tag:t.escape,color:'#cc7832'},
  {tag:t.color,color:'#6a8759',fontStyle:'italic'},
  {tag:t.url,color:'#4f86cd',textDecoration:'underline'},
  {tag:t.keyword,color:'#cc7832'},
  {tag:t.self,color:'#cc7832'},
  {tag:t.null,color:'#cc7832'},
  {tag:t.atom,color:'#cc7832'},
  {tag:t.unit,color:'#cc7832'},
  {tag:t.modifier,color:'#cc7832'},
  {tag:t.operatorKeyword,color:'#cc7832'},
  {tag:t.controlKeyword,color:'#cc7832'},
  {tag:t.definitionKeyword,color:'#cc7832'},
  {tag:t.moduleKeyword,color:'#cc7832'},
  {tag:t.operator,color:'#a9b7c6'},
  {tag:t.derefOperator,color:'#a9b7c6'},
  {tag:t.arithmeticOperator,color:'#a9b7c6'},
  {tag:t.logicOperator,color:'#a9b7c6'},
  {tag:t.bitwiseOperator,color:'#a9b7c6'},
  {tag:t.compareOperator,color:'#a9b7c6'},
  {tag:t.updateOperator,color:'#a9b7c6'},
  {tag:t.definitionOperator,color:'#a9b7c6'},
  {tag:t.typeOperator,color:'#a9b7c6'},
  {tag:t.controlOperator,color:'#a9b7c6'},
  {tag:t.punctuation,color:'#cc7832'},
  {tag:t.separator,color:'#cc7832'},
  {tag:t.bracket,color:'#a9b7c6'},
  {tag:t.angleBracket,color:'#e8bf6a'},
  {tag:t.squareBracket,color:'#a9b7c6'},
  {tag:t.paren,color:'#a9b7c6'},
  {tag:t.brace,color:'#a9b7c6'},
  {tag:t.content,color:'#a9b7c6'},
  {tag:t.heading,color:'#bbb529'},
  {tag:t.contentSeparator,color:'#80a9b7c6'},
  {tag:t.list,color:'#a9b7c6'},
  {tag:t.quote,color:'#bbb529'},
  {tag:t.emphasis,fontWeight:'bold'},
  {tag:t.strong,fontWeight:'bold'},
  {tag:t.link,color:'#4f86cd',textDecoration:'underline'},
  {tag:t.strikethrough,textDecoration:'line-through'},
  {tag:t.deleted,color:'#bbbbbb',backgroundColor:'#450505'},
  {tag:t.invalid,textDecorationLine:'underline',textDecorationStyle:'wavy',textDecorationColor:'#ff0000'},
  {tag:t.meta,color:'#bbb529'},
  {tag:t.documentMeta,color:'#bbb529'},
  {tag:t.annotation,color:'#bbb529'},
  {tag:t.processingInstruction,color:'#bbb529'},
  // {tag:t.definition(t.function),color:'#ffc66d'},
  {tag:t.constant(t.name),color:'#9876aa'},
  {tag:t.standard(t.name),fontWeight:'bold',fontStyle:'italic'},
  {tag:t.special(t.variableName),color:'#9876aa'},
  {tag:t.special(t.string),color:'#9876aa'}
]);

/// Extension to enable the One Dark theme (both the editor theme and
/// the highlight style).
export const darcula=[darculaTheme, syntaxHighlighting(darculaHighlightStyle)];
