[package]
name = "packurl"
version = "0.1.0"
authors = ["Jerome David"]
edition = "2021"

[dependencies.tokio]
version = "1.21.1"
features = [ "full" ]

[dependencies.tokio-rustls]
version = "0.23.4"

[dependencies.rcgen]
version = "0.9.3"

[dependencies.rustls]
version = "0.20.6"

[dependencies.brotli]
version = "3.3.4"

[dependencies.lazy_static]
version = "1.4.0"
